#!/bin/bash

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root. Exiting."
   exit 1
fi

# --- Network Management Detection ---
echo "Detecting network management system..."
if systemctl is-active --quiet NetworkManager; then
    echo "WARNING: NetworkManager is active. Modifying /etc/network/interfaces directly may be ignored or conflict with your settings."
elif systemctl is-active --quiet systemd-networkd; then
    echo "WARNING: systemd-networkd is active. This script is intended for ifupdown (legacy)."
elif systemctl is-active --quiet networking; then
    echo "Confirmed: 'networking' (ifupdown) service is active. Proceeding with configuration."
else
    echo "Could not identify active network manager. Proceeding with caution..."
fi
# ------------------------------------

CONFIG_FILE="interfaces.conf"

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo "Configuration file $CONFIG_FILE not found!"
    exit 1
fi

# Backup existing configuration
cp /etc/network/interfaces /etc/network/interfaces.bak

# Start building the new configuration file content
{
    echo "# Generated by auto-network-config script"
    echo "auto lo"
    echo "iface lo inet loopback"
    echo ""
} > /etc/network/interfaces

# Parse the config file and append to /etc/network/interfaces
while IFS=',' read -r interface ip_address netmask gateway; do
    # Skip lines starting with #
    [[ "$interface" =~ ^#.* ]] && continue
    [[ -z "$interface" ]] && continue

    echo "Configuring $interface..."
    {
        echo "auto $interface"
        echo "iface $interface inet static"
        echo -e "\taddress $ip_address"
        echo -e "\tnetmask $netmask"
        echo -e "\tgateway $gateway"
        echo ""
    } >> /etc/network/interfaces

done < "$CONFIG_FILE"

# Configure DNS (Updating resolv.conf)
# echo "nameserver 8.8.8.8" > /etc/resolv.conf
# echo "nameserver 8.8.4.4" >> /etc/resolv.conf

# Restart networking
echo "Restarting networking service..."
systemctl restart networking

echo "All interfaces configured successfully."